INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Overhead', 'bed1', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Lamp 1', 'bed1', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Lamp 2', 'bed1', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('TV', 'bed1', FALSE, 100);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Overhead', 'bed2', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Lamp 1', 'bed2', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Lamp 2', 'bed2', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('TV', 'bed2', FALSE, 100);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Overhead', 'bed3', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Lamp 1', 'bed3', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Lamp 2', 'bed3', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('TV', 'bed3', FALSE, 100);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Overhead', 'bath1', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Fan', 'bath1', FALSE, 30);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Overhead', 'bath2', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Fan', 'bath2', FALSE, 30);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Overhead', 'living_room', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Lamp 1', 'living_room', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Lamp 2', 'living_room', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('TV', 'living_room', FALSE, 636);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Overhead', 'kitchen', FALSE, 60);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Stove', 'kitchen', FALSE, 3500);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Oven', 'kitchen', FALSE, 4000);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Microwave', 'kitchen', FALSE, 1100);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Refrigerator', 'kitchen', FALSE, 150);
INSERT INTO appliances (name, room, isOn, power_use) VALUES ('Dishwasher', 'kitchen', FALSE, 1800);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 1', 'bed1', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 2', 'bed1', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 1', 'bed2', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 2', 'bed2', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 1', 'bed3', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 2', 'bed3', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window', 'bath1', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window', 'bath2', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 1', 'living_room', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 2', 'living_room', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 3', 'living_room', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Front Door', 'living_room', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Garage Door (into house)', 'living_room', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 1', 'kitchen', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Window 2', 'kitchen', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Back Door', 'kitchen', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Garage Door 1', 'garage', FALSE);
INSERT INTO doors_and_windows (name, room, isOpen) VALUES ('Garage Door 2', 'garage', FALSE);
INSERT INTO thermostat (unit, temp) VALUES ('celcius', 20);
